---
namespace: goodolclint
name: uptime_kuma
version: 0.2.0
readme: README.md
authors:
  - Clint Branham <goodolclint@gmail.com>
description: Ansible collection for managing Uptime Kuma monitors via its API
license:
  - GPL-3.0-or-later
tags: [monitoring, tools]

homepage: https://github.com/goodolclint/ansible-collection-uptime_kuma
repository: https://github.com/goodolclint/ansible-collection-uptime_kuma
issues: https://github.com/goodolclint/ansible-collection-uptime_kuma/issues
dependencies: {}
