---
galaxy_info:
  role_name: uptime_kuma
  author: Clint Branham
  description: Configure Uptime Kuma monitors, notifications, tags, and status pages
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - uptimekuma
    - monitoring
    - automation
dependencies: []
